### ISSUE TITLE
Bug Report: kafka-state-detector env not in Helm Chart

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#1020]
### Expected Behavior

by default kafka-state-detector should have activity and state enabled.

### Current Behavior

Both are not accessible in the Helm chart and are not set at all

### Relevant log output

```shell
{"level":"info","ts":1651076549.4356902,"caller":"kafka-state-detector/main.go:34","msg":"This is kafka-state-detector build date: 2022-04-27 16:11:40"}
{"level":"info","ts":1651076549.435948,"caller":"kafka-state-detector/main.go:51","msg":"Allowed memory size is 1073741824"}
panic: No activity or anomaly detection enabled

goroutine 1 [running]:
main.main()
	/build/cmd/kafka-state-detector/main.go:101 +0x39b
```

### Steps to Reproduce

see above

### Context (Environment)

Venice testing
prerelease7

### Version

v0.9.x

**Comment by JeremyTheocharis** [comment]
Also anomalyenabled env is missing in the code
