### ISSUE TITLE
when kafka is disabled in sensor connect and mqtt enabled the sensor connect pod crashes every couple of minutes

### ISSUE THREAD

**Issue by Sphingobium** [united-manufacturing-hub/united-manufacturing-hub#1111]
### Expected Behavior

when setting up a stack and setting mqtt-enable to true and kafka-enable to false, the mqtt messages should continuously go through and the kafka stuff should not interfere, leaving the sensorconnect module stable and running

### Current Behavior

when setting up a stack with sensor and factory cube with mqtt enable = true and kafka enable =false in sensorconnect values, the sensor connect pod crashes frequently. So sometimes mqtt messages get through to nodered and sometimes they dont. 

### Relevant log output

```shell
{"log.level":"info","@timestamp":"2022-05-18T13:49:34.968Z","log.origin":{"file.name":"sensorconnect/iolinkDeviceFinder.go","file.line":83},"message":"Found device (SN: 000201610192, PN: AL1350) at http://192.168.10.17","ecs.version":"1.6.0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6aa280]

goroutine 3354 [running]:
github.com/confluentinc/confluent-kafka-go/kafka.(*AdminClient).gethandle(0x0?)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/adminapi.go:925
github.com/confluentinc/confluent-kafka-go/kafka.getMetadata({0xc772d0?, 0x0?}, 0x0, 0xff?, 0x69ffffffff?)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/metadata.go:82 +0x7a
github.com/confluentinc/confluent-kafka-go/kafka.(*AdminClient).GetMetadata(...)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/adminapi.go:915
github.com/united-manufacturing-hub/united-manufacturing-hub/internal.GetMetaData()
	/build/internal/kafka.go:85 +0x33
github.com/united-manufacturing-hub/united-manufacturing-hub/internal.TopicExists({0xc00056cc60, 0x1f})
	/build/internal/kafka.go:58 +0x47
github.com/united-manufacturing-hub/united-manufacturing-hub/internal.CreateTopicIfNotExists({0xc00056cc60, 0x1f})
	/build/internal/kafka.go:91 +0x5b
main.GetDiscoveredDeviceInformation(0xb9?, 0xc0?)
	/build/cmd/sensorconnect/iolinkDeviceFinder.go:97 +0x438
created by main.DiscoverDevices
	/build/cmd/sensorconnect/iolinkDeviceFinder.go:55 +0xe6
```

### Steps to Reproduce

Step 1: run stack with factory cube and sensor 

step 2 : changes the values in lens for sensorconnect to mqtt-enable to true and kafka-enable to false

step 3: now the pod crashes every couple of minutes with the relevant log output

### Context (Environment)

I am currently on my second day on the job at umh and was using omh specific factory cube and sensor 

### Version

v0.9.x

**Comment by Scarjit** [comment]
Fixed by #1110
