### ISSUE TITLE
mqtt-kafka-bridge not starting

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/united-manufacturing-hub#696]
## Current Behavior

```
{"level":"info","ts":1637759551.8524628,"caller":"mqtt-to-postgresql/main.go:74","msg":"This is mqtt-to-postgresql build date: 2021-11-24 10:51:37"}
panic: open /SSL_certs/.pem: no such file or directory

goroutine 1 [running]:
main.newTLSConfig({0x0, 0x0})
	/build/cmd/mqtt-to-postgresql/mqtt.go:48 +0x36b
main.SetupMQTT({0x0, 0x0}, {0x0, 0x0}, {0xc00002c00b, 0x2}, {0xb8c398, 0xc000240070}, {0xc00002608c, 0x33})
	/build/cmd/mqtt-to-postgresql/mqtt.go:245 +0x2e5
main.main()
	/build/cmd/mqtt-to-postgresql/main.go:107 +0x72b
```
![image](https://user-images.githubusercontent.com/30755722/143245486-4d3687e8-7ccd-4892-aa37-b61bdb1f02ea.png)

## Possible solution

Is it using mqtt-to-postgresql?

**Comment by Scarjit** [comment]
@JeremyTheocharis unitedmanufacturinghub/mqtt-kafka-bridge:0.9.0-prerelease downloads mqtt-to-postgres.
Is docker hub setup correctly ?
